MainBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: MainBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

    manyToOne:
        joueur:
          targetEntity: MainBundle\Entity\Joueurs
          inversedBy: users
          cascade: ['all']

        voteoliech:
          targetEntity: MainBundle\Entity\VoteOliech
          cascade: ['all']