<?php

namespace MainBundle\Repository;

/**
 * VoteOliechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteOliechRepository extends \Doctrine\ORM\EntityRepository
{
}
