main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }


vote:
    path:     /redirect/{id}
    defaults: { _controller: MainBundle:Default:vote }

oliech_vote:
    path:     /redirectVote/{id}
    defaults: { _controller: MainBundle:Default:oliech}
